# Numpy array Operation
---

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing: ",arr[2:7])

Basic Slicing:  [3 4 5 6 7]


In [4]:
print("with step:",arr[1:8:2])

with step: [2 4 6 8]


In [6]:
print("Negative indexing: ",arr[-3])

Negative indexing:  7


## 2D array

In [8]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("2D array: \n",arr_2d)

2D array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print("specific element: ",arr_2d[1,2])

specific element:  6


In [10]:
print("Entire row: ",arr_2d[1])

Entire row:  [4 5 6]


In [11]:
print("Entire column: ",arr_2d[:,1])

Entire column:  [2 5 8]


## Sorting

In [2]:
unsorted = np.array([1,3,4,5,34,32,43,4,54,5,3,2])
print("sorted array: ",np.sort(unsorted))

sorted array:  [ 1  2  3  3  4  4  5  5 32 34 43 54]


In [6]:
arr_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
print("2D unsorted array:\n",arr_2d_unsorted)
print("\nsorted 2D array by column:\n",np.sort(arr_2d_unsorted,axis=0))
print("\nsorted 2D array by row:\n",np.sort(arr_2d_unsorted,axis=1))

2D unsorted array:
 [[3 1]
 [1 2]
 [2 3]]

sorted 2D array by column:
 [[1 1]
 [2 2]
 [3 3]]

sorted 2D array by row:
 [[1 3]
 [1 2]
 [2 3]]


## filter

In [7]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number=numbers[numbers%2==0]
print("Even number",even_number)

Even number [ 2  4  6  8 10]


## filter with mask

In [8]:
mask = numbers > 5
print("numbers greater than 5: ",numbers[mask])

numbers greater than 5:  [ 6  7  8  9 10]


## fancy indexing vs np.where()