### Numpy array and basics

In [2]:
import numpy as np

### creating array from list 

In [4]:
arr_1d=np.array([10, 20, 30, 40, 50])
print("1D array : ",arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D array : ",arr_2d)


1D array :  [10 20 30 40 50]
2D array :  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [7]:
py_list=[1,2,3]
print("python list multiplication: ",py_list *2)

np_array=np.array([1,2,3])
print("Python array muliplication: ",np_array*2)

python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array muliplication:  [2 4 6]


In [11]:
import time
start = time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List opertion time: ",time.time()-start)

start=time.time()
np_array=np.arange(1000000)*2
print("\n Numpy opertion time: ",time.time()-start)



 List opertion time:  0.26552915573120117

 Numpy opertion time:  0.027622222900390625


# creating array from scratch
---
## zeros array

In [12]:
zeros=np.zeros((3,4))
print("zeros array: \n",zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## ones array

In [14]:
ones = np.ones((2,3))
print("one arrry : \n",ones)

one arrry : 
 [[1. 1. 1.]
 [1. 1. 1.]]


## full array

In [15]:
full =np.full((2,2),7)
print("full array: \n",full)

full array: 
 [[7 7]
 [7 7]]


## random array

In [17]:
random = np.random.random((2,3))
print("random array : \n",random)

random array : 
 [[0.95716753 0.7496068  0.98301065]
 [0.51055139 0.62157553 0.64288612]]


## sequence array

In [18]:
sequence=np.arange(0,10,2)
print("sequence array: \n",sequence)

sequence array: 
 [0 2 4 6 8]
