# Numpy array Operation
---

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing: ",arr[2:7])

Basic Slicing:  [3 4 5 6 7]


In [4]:
print("with step:",arr[1:8:2])

with step: [2 4 6 8]


In [6]:
print("Negative indexing: ",arr[-3])

Negative indexing:  7


## 2D array

In [8]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("2D array: \n",arr_2d)

2D array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print("specific element: ",arr_2d[1,2])

specific element:  6


In [10]:
print("Entire row: ",arr_2d[1])

Entire row:  [4 5 6]


In [11]:
print("Entire column: ",arr_2d[:,1])

Entire column:  [2 5 8]
